criteria:
  Battery:
    direction: max
    q: 250
    v: 3500
    weight: 0.25
  Camera:
    direction: max
    q: 2
    v: 150
    weight: 0.25
  Processor:
    direction: max
    q: 0
    v: 0
    weight: 0.0
  RAM:
    direction: max
    q: 0
    v: 0
    weight: 0.0
  Weight:
    direction: min
    q: 0
    v: 220
    weight: 0.5
