criteria:
  Battery:
    direction: max
    q: 1000
    v: 4000
    weight: 0.2
  Camera:
    direction: max
    q: 0
    v: 0
    weight: 0.0
  Processor:
    direction: max
    q: 100000
    v: 1800000
    weight: 0.4
  RAM:
    direction: max
    q: 0
    v: 12
    weight: 0.3
  Weight:
    direction: min
    q: 15
    v: 250
    weight: 0.1
